printWidth: 100
useTabs: false
tabWidth: 4
singleQuote: true
semi: true
jsxSingleQuote: true
quoteProps: as-needed
trailingComma: none
bracketSpacing: true
bracketSameLine: false
plugins:
  - prettier-plugin-prisma