// One-shot splice helper for the set-consolidation pipeline: merges the
// redirect pairs printed by scripts/applySetMerges.ts (captured in the given
// file) into src/lib/cardRedirects.ts — 301s for merged card URLs and whole
// /sets/{loser} shells. Unlike _spliceRedirects.mjs this UNIONs with existing
// entries (the capture only holds the new pairs) and keeps both lists sorted +
// deduped. Idempotent — safe to re-run.
// Usage: node scripts/_spliceSetRedirects.mjs <pairs-file>
import { readFileSync, writeFileSync } from 'node:fs';

const source = process.argv[2];
if (!source) throw new Error('usage: node scripts/_spliceSetRedirects.mjs <pairs-file>');

const captured = readFileSync(source, 'utf8').split('\n');
const capture = (prefix) =>
    [
        ...new Set(
            captured
                .filter((l) => l.includes(`{ source: '${prefix}`))
                .map((l) => l.trim().replace(/,+$/, ''))
        )
    ];
const newCardPairs = capture('/cards/');
const newSetPairs = capture('/sets/');
console.log(`captured ${newCardPairs.length} card pairs + ${newSetPairs.length} set pairs from ${source}`);

const path = 'src/lib/cardRedirects.ts';
const src = readFileSync(path, 'utf8');

const cardStart = src.indexOf('export const cardRedirects: LegacyRedirect[] = [');
const rawSetStart = src.indexOf('export const setRedirects: LegacyRedirect[] = [');
if (cardStart < 0) throw new Error('cardRedirects array not found');
const cardEnd = src.indexOf('];', cardStart) + 2;
const setEnd = rawSetStart < 0 ? cardEnd : src.indexOf('];', rawSetStart) + 2;

const extractPairs = (text) =>
    [
        ...new Set(
            text
                .split('\n')
                .filter((l) => l.includes("{ source: '"))
                .map((l) => l.trim().replace(/,+$/, ''))
        )
    ];
const existingCardPairs = extractPairs(src.slice(cardStart, cardEnd));
const existingSetPairs = rawSetStart < 0 ? [] : extractPairs(src.slice(rawSetStart, setEnd));

const cardPairs = [...new Set([...existingCardPairs, ...newCardPairs])].sort();
const setPairs = [...new Set([...existingSetPairs, ...newSetPairs])].sort();

const cardBlock =
    `export const cardRedirects: LegacyRedirect[] = [\n` +
    `    // ${cardPairs.length} pairs generated by scripts/applyMerges.ts + scripts/applySetMerges.ts — do not edit by hand\n` +
    cardPairs.map((p) => `    ${p},`).join('\n') +
    '\n];';
const setBlock =
    `\n\n/**\n` +
    ` * Whole-set 301s for set shells absorbed by the set-consolidation pipeline\n` +
    ` * (scripts/applySetMerges.ts). Wired into next.config.ts alongside\n` +
    ` * \`cardRedirects\` so link equity consolidates onto the keeper set.\n` +
    ` */\n` +
    `export const setRedirects: LegacyRedirect[] = [\n` +
    `    // ${setPairs.length} pairs generated by scripts/applySetMerges.ts — do not edit by hand\n` +
    setPairs.map((p) => `    ${p},`).join('\n') +
    '\n];';

writeFileSync(path, src.slice(0, cardStart) + cardBlock + setBlock + src.slice(Math.max(cardEnd, setEnd)));
console.log(
    `spliced ${cardPairs.length} card pairs + ${setPairs.length} set pairs into ${path} (was ${existingCardPairs.length} + ${existingSetPairs.length})`
);