// One-shot splice helper for the dedupe pipeline: rebuilds the `cardRedirects`
// array in src/lib/cardRedirects.ts from the pairs printed by applyMerges
// (captured in the given file). Usage: node scripts/_spliceRedirects.mjs <pairs-file>
import { readFileSync, writeFileSync } from 'node:fs';

const source = process.argv[2] ?? '/tmp/dryrun2.txt';
const pairs = [
    ...new Set(
        readFileSync(source, 'utf8')
            .split('\n')
            .filter((l) => l.includes("{ source: '/cards/"))
            .map((l) => l.trim())
    )
].sort();

const path = 'src/lib/cardRedirects.ts';
const src = readFileSync(path, 'utf8');
const start = src.indexOf('export const cardRedirects: LegacyRedirect[] = [');
const end = src.indexOf('];', start);
if (start < 0 || end < 0) throw new Error('cardRedirects array not found');

const body =
    `export const cardRedirects: LegacyRedirect[] = [\n` +
    `    // ${pairs.length} pairs generated by scripts/applyMerges.ts — do not edit by hand\n` +
    pairs.map((p) => `    ${p}`).join('\n') +
    '\n';
writeFileSync(path, src.slice(0, start) + body + src.slice(end));
console.log(`spliced ${pairs.length} redirect pairs into ${path}`);
